### PR TITLE
Fixes #1

### LINKED ISSUE #1: Eliminate trailing whitespace in .html files
I really enjoy these notebooks so far and can't wait to experiment with them. Super minor issue: this is probably a dated approach, but you can eliminate trailing whitespace from your knitted .html files by adding the below html code to the final line of the .Rmd file: 

```<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>```

I think there might even be a short R function now to do so, but this was my goto for years to keep notebook scrolling snappy and tight.

### PR DESCRIPTION
**Pull request by asteves**
Fixes #1

### CODE REVIEW

**Comment by asteves** [comment]
@aculich I don't know if this actually needs a review, but for process purposes I'm tagging you.

**Comment by asteves** [comment]
@pssachdeva Based on Aaron's reply, I'm tagging you for a review here.

**Comment by aculich** [comment]
@asteves I appreciate you tagging me in these as we get the process started, but going forward in general I'll just keep tabs on things via the [#github-activity](https://dlab-berkeley.slack.com/archives/C018R2ZMH2N) channel on slack that gives me the play-by-play automated feed from https://github.com/dlab-berkeley/ as people open/close issues and PRs.

But _**do tag me**_ if there's something in particular I should look at, weigh in on, or otherwise track more closely. There are some things like issues with datahub that I want to actively be a subscriber on so I get email notifications about it.

Thanks!

**Comment by asteves** [comment]
Will do. Misread the new GitHub PR requirements. Apologies for the double
post spam.

**Pull request merged**
